# Unbind the default prefix
unbind C-b

# Set Ctrl + Space as the new prefix
set-option -g prefix C-Space
bind C-Space send-prefix

set -g base-index 1 #window index start with 1 not 0

set -g renumber-windows on # renumber windows if one is deleted

unbind r
bind r source-file ~/.tmux.conf

# Enable mouse support
set -g mouse on

# Split panes with leader + k/lunbind '"'
unbind %
bind k split-window -v
bind l split-window -h





#hide all open panel exept the focused one 
bind-key h resize-pane -Z



# Resize pane with Option(Alt) + Arrow keys
bind -n M-h  resize-pane -L 5
bind -n M-l resize-pane -R 5
bind -n M-k    resize-pane -U 5
bind -n M-j  resize-pane -D 5




# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"

bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-j' if-shell "$is_vim" 'send-keys C-j'  'select-pane -D'
bind-key -n 'C-k' if-shell "$is_vim" 'send-keys C-k'  'select-pane -U'
bind-key -n 'C-l' if-shell "$is_vim" 'send-keys C-l'  'select-pane -R'



# Restore clear screen keybind mapped over by tmux-navigator
bind-key -n 'C-\' if-shell "$is_vim" 'send-keys C-\\'  'send-keys C-l'

# Copy mode bindings
bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-j' select-pane -D
bind-key -T copy-mode-vi 'C-k' select-pane -U
bind-key -T copy-mode-vi 'C-l' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l














# Tell tmux to use 24-bit color
set-option -ga terminal-overrides ',*:Tc'

# Set the TERM variable correctly
set -g default-terminal "tmux-256color"


#set status bar at the top
set -g status-position top

# List of plugins
set -g @plugin 'tmux-plugins/tpm'

set -g @plugin 'Nybkox/tmux-kanagawa'
set -g @kanagawa-theme 'dragon'




# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'









# Override the theme's background color
set-option -g status-style "bg=black fg=white"
set-option -g window-style "bg=black"
set-option -g window-active-style "bg=black"

# Add these lines to force white text
set-option -g pane-active-border-style "fg=white"
set-option -g pane-border-style "fg=white"
set-option -g window-status-style "fg=white"
set-option -g window-status-current-style "fg=white,bold"

# Rounded corners
set -g @kanagawa-left-icon-padding 0
set -g @kanagawa-right-icon-padding 0
set -g @kanagawa-show-powerline true
set -g @kanagawa-show-left-sep ''
set -g @kanagawa-show-right-sep ''

set -g status-left "#[fg=#{?client_prefix,#c1b38f,#393836}]#[bg=black]#[fg=#{?client_prefix,black,#79846c}]#{?client_prefix,#[bg=#c1b38f],#[bg=#393836]}  #[fg=#{?client_prefix,#c1b38f,#393836}]#[bg=black] "
set -g status-right "#[fg=#c4b28a,bg=black]#[fg=black,bg=#c4b28a] #(~/.tmux/plugins/tmux-kanagawa/scripts/battery.sh) #[fg=#c1b38f,bg=#393836] #(~/.tmux/plugins/tmux-kanagawa/scripts/battery.sh percent) #[fg=#393836,bg=black] #[fg=#949fb5,bg=black]#[fg=black,bg=#949fb5] #(~/.tmux/plugins/tmux-kanagawa/scripts/network.sh) #[fg=black,bg=#949fb5] #[fg=#969fb3,bg=#393836] #(ipconfig getsummary en0 | awk -F ' SSID : ' '/ SSID : / {print $2}' | xargs) #[fg=#393836,bg=black] #[fg=#8c9f78,bg=black]#[fg=black,bg=#8c9f78]  #[fg=#8c9f78,bg=#393836] %m-%d | %I:%M %p #[fg=#393836,bg=black]"
set -g window-status-current-format "#[fg=#b97871,bg=black]#[fg=black,bg=#b97871] #I #[fg=#b97871,bg=#393836] #W #[fg=#393836,bg=black]"
set -g window-status-format "#[fg=#949fb5,bg=black]#[fg=black,bg=#949fb5] #I #[fg=#949fb5,bg=#393836] #W #[fg=#393836,bg=black]"
