[window]
option_as_alt = "both"

[font]
normal.family = "FiraMono Nerd Font"
size = 16

# Kanagawa Dragon Color Scheme for Alacritty
######################################################
[colors]
  [colors.primary]
    background = "#000000"
    foreground = "#c5c9c5"

  [colors.normal]
    black   = "#0d0c0c"
    red     = "#c4746e"
    green   = "#8a9a7b"
    yellow  = "#c4b28a"
    blue    = "#8ba4b0"
    magenta = "#a292a3"
    cyan    = "#8ea4a2"
    white   = "#C8C093"

  [colors.bright]
    black   = "#a6a69c"
    red     = "#E46876"
    green   = "#87a987"
    yellow  = "#E6C384"
    blue    = "#7FB4CA"
    magenta = "#938AA9"
    cyan    = "#7AA89F"
    white   = "#c5c9c5"

  [colors.selection]
    background = "#2D4F67"
    foreground = "#C8C093"
######################################################

# Nordic Color Scheme for Alacritty (Exact match with nordic.nvim)
######################################################
# [colors]
#   [colors.primary]
#     background = "#242933"    # gray0 - exact match from nordic.nvim
#     foreground = "#BBC3D4"    # white0_normal - exact match from nordic.nvim
#
#   [colors.normal]
#     black   = "#3B4252"       # gray2
#     red     = "#BF616A"       # red.base
#     green   = "#A3BE8C"       # green.base
#     yellow  = "#EBCB8B"       # yellow.base
#     blue    = "#81A1C1"       # blue1
#     magenta = "#B48EAD"       # magenta.base
#     cyan    = "#8FBCBB"       # cyan.base
#     white   = "#E5E9F0"       # white2
#
#   [colors.bright]
#     black   = "#4C566A"       # gray4
#     red     = "#C5727A"       # red.bright
#     green   = "#B1C89D"       # green.bright
#     yellow  = "#EFD49F"       # yellow.bright
#     blue    = "#88C0D0"       # blue2
#     magenta = "#BE9DB8"       # magenta.bright
#     cyan    = "#9FC6C5"       # cyan.bright
#     white   = "#ECEFF4"       # white3
#
#   [colors.selection]
#     background = "#4C566A"    # gray4
#     foreground = "#D8DEE9"    # white1
######################################################
